### PR TITLE
crc32:Improve the cold performance for neoverse n1

### PR DESCRIPTION
**Pull request by haoyu01**
This version improve about 30% at cold test .

### CODE REVIEW

**Comment by haoyu01** [comment]
@gbtucker  please review

**Comment by gbtucker** [comment]
The commit message isn't descriptive.  What does the commit do?  The why can go in the detailed description but what it does should be first.

**Comment by haoyu01** [comment]
@gbtucker just update commit message . Please review

**Comment by gbtucker** [comment]
OK, thanks. I understand now.  I'll queue for integration.

**Comment by haoyu01** [comment]
@gbtucker , Travis CI is not triggered automatic  for this PR . And I trigger it at https://travis-ci.org/github/haoyu01/isa-l/pull_requests . It looks pass . 

Please check it

**Comment by gbtucker** [comment]
Thanks, not sure why it never triggered.

**Comment by haoyu01** [comment]
Thanks @gbtucker

**Pull request merged**
