### PR TITLE
Fix build issues

### PR DESCRIPTION
**Pull request by haoyu01**
- fix strict prototype waring
- fix cross compile error

### CODE REVIEW

**Comment by haoyu01** [comment]
@gbtucker , Please review .

**Comment by gbtucker** [comment]
@haoyu01 I ran a nearly identical fix to 44fbfb3 and it failed all the drone.io builds using clang  [drone.io build](https://cloud.drone.io/gbtucker/isa-l/9).

I think your asm only works for gnu asm and the clang builds in drone.io are currently using gcc to build .S files before linking with clang.  Is it possible to fix the clang asm also or should we remove the clang builds from drone.io?

**Comment by haoyu01** [comment]
> 
> 
> @haoyu01 I ran a nearly identical fix to [44fbfb3](https://github.com/intel/isa-l/commit/44fbfb3fc3e063b1193af95e82067408e9f83c6c) and it failed all the drone.io builds using clang [drone.io build](https://cloud.drone.io/gbtucker/isa-l/9).
> 
> I think your asm only works for gnu asm and the clang builds in drone.io are currently using gcc to build .S files before linking with clang. Is it possible to fix the clang asm also or should we remove the clang builds from drone.io?

I will check clang build and fix it .

**Comment by haoyu01** [comment]
@gbtucker , just fix clang issue . please review it .

**Comment by gbtucker** [comment]
Clang still complains with
```
crc/aarch64/crc32_gzip_refl_hw_fold.S:54:2: error: unknown directive
 .arch armv8-a+crc+crypto
 ^
```
After combining with travis update. https://travis-ci.org/gbtucker/isa-l/builds/602443738

**Comment by haoyu01** [comment]
@gbtucker , update it and fix clang build error

**Comment by haoyu01** [comment]
It looks OSX build always fail at `brew install yasm` now .

**Comment by gbtucker** [comment]
Travis brew install should be fixed.  All looks good except by comments in #107 for "build: fix compile break issues."  Suggest as_filter = ${CC} -D__ASSEMBLY__ and consider gcc a min requirement.

**Comment by haoyu01** [comment]
@gbtucker ,
just remove clang support , please review

**Pull request merged**
