### PR TITLE
Implement adler32 with Arm64 Neon

### PR DESCRIPTION
**Pull request by haoyu01**
1. Enable IGZIP for aarch64
1. Implement Adler32 with neon

### CODE REVIEW

**Comment by haoyu01** [comment]
@gbtucker , This is adler32 for arm64 . Please review that .

**Comment by gbtucker** [comment]
Does this need an updated multi-binary to select for features?

**Comment by haoyu01** [comment]
@gbtucker ， 
Yes . 
Not only this patch . I am preparing multi-binary select patch . This patch and some of other patch should be rebase later .

**Comment by haoyu01** [comment]
@gbtucker , 
I upload two new patches . And this  patch will be updated  after  #84 merged

**Comment by haoyu01** [comment]
close it due to wrong operation

**Pull request closed without merging**
