### PR TITLE
Enable ErasureCode on ppc64le with altivec intrinsics

### PR DESCRIPTION
**Pull request by winice-test**
Enable ISA-L erasurecode on ppc64le by using Altivec intrinsics.

Signed-off-by: Hong Bo Peng <penghb@cn.ibm.com>
Thanks-to: Daniel Axtens <dja@axtens.net>

Daniel contributed the idea to select the implementation of dot-product with VSX. He confirmed that it is appropriate to add him as "Thanks-to".

### CODE REVIEW

**Comment by gbtucker** [comment]
Thanks Hong, on first look it seems together except for some formatting issues.

The signoff needs to be in the commit message and standard format (see CONTRIBUTING.md).
The commit email address doesn't match the PR signoff.
The breakup into patches seems arbitrary and the first commit will not build on its own.  Consider squashing the two commits.
C file formatting doesn't pass.  Need to run `./tools/iindent erasure_code/ppc64le/*.c` and `./tools/check_format.sh`.

**Comment by winice-test** [comment]
Thank you for your quick response. I have updated for some of the issues such as the sign-off msg and squash 2 commits.
But regarding to the other 2:
>>> The commit email address doesn't match the PR signoff.I am working for IBM China. I registered in github.com long time ago with my personal email address. But this activity is my part of work in IBM. So I have to use my email address in IBM. And also as the CONTRIBUTING.md said I need to input real name. I associated my personal email address with my IBM mail address.
>>> C file formatting doesn't pass. Need to run ./tools/iindent erasure_code/ppc64le/*.c and ./tools/check_format.sh.I ran tools/iindent erasure_code/ppc64le/*.c. Nothing is reported and return code is 0.penghb@phbw7dsk2:~/isa-l$ tools/iindent erasure_code/ppc64le/*.cpenghb@phbw7dsk2:~/isa-l$ echo $?0
And I also tried to run check_format. But it looks like my indent version doesn't match the minimal requirement (2.2.12). I am working on Ubuntu 16.04 with indent 2.2.11. I have to find a newer indent before running this check. 
Or I changed the 2.2.12 to 2.2.11 in the script. Then it reportspenghb@phbw7dsk2:~/isa-l$ ./tools/check_format.shChecking format of files in the git index at /home/penghb/isa-lChecking C files for coding style...  File found with formatting issues: igzip/igzip.c  File found with formatting issues: programs/igzip_cli.c  Run ./tools/iindent on filesChecking for dos and whitespace violations...Checking source files for permissions...fatal: There is nothing to exclude from by :(exclude) patterns.Perhaps you forgot to add either ':/' or '.' ?Checking script files for permissions...Checking for signoff in commit message...Format Failpenghb@phbw7dsk2:~/isa-l$ echo $?1
No failure was caught in erasure_code/ppc64le.
Best Regards!
Winice


----- 原始邮件 -----
发件人：Greg Tucker <notifications@github.com>
收件人：intel/isa-l <isa-l@noreply.github.com>
抄送人：winice <winice@sina.com>,  Author <author@noreply.github.com>
主题：Re: [intel/isa-l] Enable ErasureCode on ppc64le with altivec intrinsics (#125)
日期：2020年02月19日 07点28分

Thanks Hong, on first look it seems together except for some formatting issues.
The signoff needs to be in the commit message and standard format (see CONTRIBUTING.md).

The commit email address doesn't match the PR signoff.

The breakup into patches seems arbitrary and the first commit will not build on its own.  Consider squashing the two commits.

C file formatting doesn't pass.  Need to run ./tools/iindent erasure_code/ppc64le/*.c and ./tools/check_format.sh.

**Comment by gbtucker** [comment]
> >> The commit email address doesn't match the PR signoff.

> I am working for IBM China. I registered in github.com long time ago with my personal email address. But this activity is my part of work in IBM. So I have to use my email address in IBM. And also as the CONTRIBUTING.md said I need to input real name. I associated my personal email address with my IBM mail address.

No I think you misunderstood.  The commit says Author: Hong Bo Peng `<penghb@phb-mbp.local>`  Likely the global .gitconfig user.email had not been set and picked up the local machine name.  If you set user.name= Hong Bo Peng, and user.email=penghb@cn.ibm.com, then a `git commit --amend --signoff --reset-author` will fix both the email and the signoff format issue.

> >> C file formatting doesn't pass. ...

> I ran tools/iindent erasure_code/ppc64le/*.c. Nothing is reported and return code is 0. 

You do need indent 2.2.12 to check format.  If it is difficult to find the right .deb, it is simple to build from source.  I think the issue is spaces instead of tabs.

**Comment by winice-test** [comment]
Thank you. I installed the indent version 2.2.12 debian package directly. Now both check pass. I didn't see the space issue. Can you share with me some more detail information?

penghb@phbw7dsk2:~/isa-l$ indent --version
GNU indent 2.2.12
penghb@phbw7dsk2:~/isa-l$ ./tools/iindent erasure_code/ppc64le/*.?
penghb@phbw7dsk2:~/isa-l$ ./tools/check_format.sh
Checking format of files in the git index at /home/penghb/isa-l
Checking C files for coding style...
Checking for dos and whitespace violations...
Checking source files for permissions...
fatal: There is nothing to exclude from by :(exclude) patterns.
Perhaps you forgot to add either ':/' or '.' ?
Checking script files for permissions...
Checking for signoff in commit message...
Format Pass

**Comment by gbtucker** [comment]
I looked at the latest push 286656b and the name and signoff are fixed.  It fails check_format however.  Perhaps the files fixed with ./tools/iindent were not commited.

It looks like you accidentally squashed an upstream patch into your commit. a3d5cd8 is just a one line change but got incorporated into your commit.

**Comment by winice-test** [comment]
OK. Now I reversed the igzip/igzip.c in commit a3d5cd8 .

And I also do the format check in a Ubuntu 18.04 docker image. Everything passed now. Please check.

```
root@8c274a80ed69:~/isa-l# indent --version
GNU indent 2.2.12
root@8c274a80ed69:~/isa-l# tools/iindent erasure_code/ppc64le/*.c
root@8c274a80ed69:~/isa-l# tools/iindent erasure_code/ppc64le/*.h
root@8c274a80ed69:~/isa-l# tools/check_format.sh
Checking format of files in the git index at /root/isa-l
Checking C files for coding style...
Checking for dos and whitespace violations...
Checking source files for permissions...
Checking script files for permissions...
Checking for signoff in commit message...
Format Pass
```

**Comment by gbtucker** [comment]
Checked and the squashed commit has been pulled out, thanks.  Format errors are still in the code however.

From the sequence of commands you listed, perhaps it is not clear that the ./tools/iindent script will change the C files specified so they are consistent format with all other code.  As changes they will need to be committed.  A `git diff` could confirm.

**Comment by winice-test** [comment]
Sorry for the format errors. I do check manually for the files and submit again. Please review.

Thank you for your patience.

**Comment by gbtucker** [comment]
Looks OK, I'll run it through internal tests.

**Comment by gbtucker** [comment]
Integrated.

**Comment by winice-test** [comment]
Thank you for all the support.

**Pull request closed without merging**
