### PR TITLE
ci: remove unused drone configuration

### PR DESCRIPTION
**Pull request by haoyu01**

### CODE REVIEW

**Comment by haoyu01** [comment]
@gbtucker , please review

**Comment by gbtucker** [comment]
Is there an issue with it?  I think it still works on personal branches.

**Comment by haoyu01** [comment]
> 
> 
> Is there an issue with it? I think it still works on personal branches.

Drone still works. Travis-CI can do same thing . I just want to remove duplicate CI configuration .

**Comment by gbtucker** [comment]
OK, I'll queue this for integration.

**Comment by gbtucker** [comment]
Integrated.

**Pull request closed without merging**
