### PR TITLE
Create correct zlib header

### LINKED ISSUE #177: Compressing zlib data with isal
This is an issue I encountered when working on the python bindings.

When creating a `isal_zstream` and setting `gzip_flag` to `IGZIP_ZLIB` hist_bits is effectively always 15, even when set to another value. I noticed because I could not decompress using zlib

### PR DESCRIPTION
**Pull request by rhpvorderman**
Fixes #177

~~This code reuses the isal_write_zlib_header function in the write_stream_header functions.~~
~~This PR is currently in draft state. My testing indicates that there are issues with flushing when this is implemented.~~

EDIT: My first attempt relied on isal_write_zlib_header but created some issues in flushing. My second attempt here creates a new function that creates a pointer with the correct header. It is a simpler solution that creates less problems.

Still there are two problems:
- the zlib header is not constant, but the gzip header is. (Which creates a compiler warning.)
- the zlib header creates a pointer of size 2 which is never freed. A memory leak.

This is my first time writing pure C. I have no experience in elegantly handling these problems. I made some attempts but these all ended in errors.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
@gbtucker Thanks for the pointer. I created an uint8_t array of length 10 as a buffer. A gzip header was used to initialise it. (I could have used zeroes to initialize but since the gzip header is mostly fixed it seemed more straightforward to do it this way). The zlib header is created by manipulatiing the first two bytes in the buffer. These are the only bytes that are copied anyway. 

I also added code to correctly set the XFL byte in the gzip header to 0x04 when the level 0 (fastest algortitm) is used.

**Comment by gbtucker** [comment]
Thanks for the contribution @rhpvorderman.  Don't worry about the release_notes but would need signoff and formatting as specified in [CONTRIBUTING.md](https://github.com/intel/isa-l/blob/master/CONTRIBUTING.md).

**Comment by rhpvorderman** [comment]
@gbtucker Thank you. I corrected the formatting issues squashed the commit, signed it and signed off on it.

**Comment by gbtucker** [comment]
Thanks.  I'll start running it through extended testing.  Would you mind if we shorten the commit title line? Format is throwing off some internal tools.

**Comment by rhpvorderman** [comment]
@gbtucker. Thanks! No, I don't mind. I shortened the title to <50 characters myself and force pushed the commit.

**Comment by gbtucker** [comment]
Thanks again @rhpvorderman, I'll schedule this for integration.

**Comment by rhpvorderman** [comment]
Thank you and thank you for patience and positive feedback on my first C PR.

**Comment by gbtucker** [comment]
Integrated

**Pull request closed without merging**
