### PR TITLE
igzip: Implement deflate body/finish with arm64 assembly

### PR DESCRIPTION
**Pull request by haoyu01**
Arm64 assembly version deflate body/finish

### CODE REVIEW

**Comment by haoyu01** [comment]
@gbtucker , please review

**Comment by gbtucker** [comment]
Thanks, I'm not sure why travis is failing.  I'll try to restart and run internal tests.

**Comment by haoyu01** [comment]
Thanks , @gbtucker 

I am not sure if you catch below points . 

Travis CI build for #91 mark this PR fail .   
- Build 172 fail and the build is for PR #91 .
- Build 169 is for this PR .
- PR #91 has been closed .

**Comment by haoyu01** [comment]
@gbtucker .
sorry , I do wrong operation .

**Comment by gbtucker** [comment]
Integrated.

**Pull request closed without merging**
