### PR TITLE
fix clang build issues

### PR DESCRIPTION
**Pull request by yuhaoth**
This is fix for #166 and fix warning for clang .

### CODE REVIEW

**Comment by yuhaoth** [comment]
@gbtucker  please review

**Comment by yuhaoth** [comment]
@gbtucker ，Any idea about this patch?

**Comment by gbtucker** [comment]
@yuhaoth, I'm not sure this is the best way to fix the sanitizer warning.  It does look like the catch is NULL+0.  I don't quite understand the cases when the pointer is null.  I think there may be a better way to solve by check initial conditions once rather then just keep skipping.

**Comment by yuhaoth** [comment]
Okay, I will abandon it

**Pull request closed without merging**
