### PR TITLE
erasure_code: modify perf benchmark loop

### LINKED ISSUE #100: ec performance of small blocksize is worse when including init time
By using `erasure_code_perf`, the performance of small blocksize, like 1KB, is even worse than other larger size. This happens because it includes the initial operation (and other operations when decode) in the benchmark range.  So will it be better to move other funcs than `ec_encode_data`  out of the benchmark range?

### PR DESCRIPTION
**Pull request by egggHang**
Fixes #100 
Modify the benchmark loop in `erasure_code_perf`， just time the `ec_encode_data()` function.

Signed-off-by: Hang Li <lihang48@hisilicon.com>

### CODE REVIEW

**Comment by egggHang** [comment]
@gbtucker Would you please help to review this patch? thanks.

**Comment by gbtucker** [comment]
Thanks, looks like just as discussed in #100.  Just has a few formatting issues.  Some blank lines were removed from the header and need to run `../tools/iindent erasure_code/erasure_code_perf.c`

**Comment by egggHang** [comment]
@gbtucker， I have recorverd the header and run iindent,  but there is still one fail in travi-ci, would you please help to review again? thanks.

**Comment by gbtucker** [comment]
Integrated

**Pull request closed without merging**
