### PR TITLE
crc: implement table-driven crc algorithm

### PR DESCRIPTION
**Pull request by zhiyuan-zhu**
Change-Id: Iebfb8ae1db09bf2dc882fd87e61627d74fab4a5c
Signed-off-by: Zhiyuan Zhu <zhiyuan.zhu@arm.com>

Reopen a new PR for: https://github.com/01org/isa-l/pull/63

### CODE REVIEW

**Comment by zhiyuan-zhu** [comment]
@gbtucker 

CI build failed using the option "C_COMPILER=clang" on intel CI system,
After check the log, crc test all passed, but igzip test fail,
And I can't find the file: ./build-aux/test-driver in isa-l's source code,
Would you please help to check it? thanks a lot.
...
PASS: crc/crc16_t10dif_test
PASS: crc/crc16_t10dif_copy_test
PASS: crc/crc64_funcs_test
PASS: crc/crc32_funcs_test
./build-aux/test-driver: line 107: 15101 Illegal instruction     (core dumped) "$@" > $log_file 2>&1
FAIL: igzip/igzip_rand_test

**Comment by gbtucker** [comment]
We looked into the build failure and it is just the sanitizer catching an odd case of non-explicit unaligned load.  We have a patch that will fix and will push shortly.

**Comment by zhiyuan-zhu** [comment]
Thanks a lot, I will  "push -f"  this patch  after your patch applied.

**Comment by zhiyuan-zhu** [comment]
@gbtucker 

crc_base.c/crc64_base.c now contains table-driven code, original crc_base.c/crc64_base.c is renamed to crc_ref.c, add the table driven test in the respective test code files.

**Comment by gbtucker** [comment]
rebased and integrated

**Pull request closed without merging**
